### PR TITLE
displaying words on card bug

### PR DESCRIPTION
**Pull request by DihyahAdib**
its saying either that i cant destructor word, or that word isnt defined, or it just doesnt show up at all
image
image
these are the two ways ive tried doing it

### CODE REVIEW

**Comment by DihyahAdib** [comment]
also my internet is very bad keeps disconnecting idk if i can call today

**Comment by nickmanning214** [comment]
I see these two images are your two attempts to fix the issue. I liked in the second one you changed the name to "wordObj". That gets rid of the confusion where a `word` object contains a `word` property. As a further suggestion, "word" is still vague and "definition" is misnamed. It's not really a definition - it's still a word, just translated. Maybe `word` or `wordObj` could have two properties: `yourLang` and `foreignLang`, mirroring how the UI names it. As a rule of thumb, the easiest way to remember something while coding is to name it the same way the UI names it.

So in your first attempt, it seems you tried to change the function to accept the `wordBank` instead of a single word. Seems like in your second attempt you undid that. I think it was a good idea to undo that, because the function is supposed to simply convert a `wordObj` to the `word: definition` format, and you don't need the whole `wordBank` to do that.

As an additional educational point, that wouldn't be the right way to destructure an array. To destructure `wordBank` it would look like this: 

`const [word1, word2, word3] = wordBank`. This would give you three words as variables for example. But like you eventually realized, you want to destructure a single word, not the entire wordBank.

Your last approach actually works for me when I try it in the code. Are you still seeing the error?

But from an architectural perspective, this isn't how I'd personally solve the issue. You have to ask yourself, do you want to be able to pass `undefined` to this function, and have it output a fallback? Ideally, this would never happen in your app. If we are passing undefined, that's the first issue. 
Screenshot 2024-11-27 at 9 18 15 PM
 
I see this in the console and I trace it back to this line in `updateUI`:

Screenshot 2024-11-27 at 9 18 49 PM

Turns out we are trying to set the `flash-card` text to `wordBank[cardIndex]`, but what if `wordBank` is an empty array, as it is when the app is opened for the first time? You have to ask yourself: what do you want the behavior of the app to be when the user hasn't added flash cards yet? My suggestion is: if the user hasn't added any flashcards yet, don't allow them to open casual mode at all. Instead, prompt them that they must add words before using casual mode. But that's just a suggestion - go with whatever you had in mind!

**Comment by nickmanning214** [comment]
Let me know if this makes sense or if you have any questions!

**Comment by DihyahAdib** [comment]
I THINK i actually fixed my internet, its so good now

**Comment by DihyahAdib** [comment]
yea i tried making it a fall back by passing some strings into the word = "" and definition = "" and it worked for a bit. when i didnt have words those nothing showed up and when i did the words showed up but after woking on the app a bit more randomly i started getting that error again

> Your last approach actually works for me when I try it in the code. Are you still seeing the error?
yea so it worked until it didnt.

> My suggestion is: if the user hasn't added any flashcards yet, don't allow them to open casual mode at all. Instead, prompt them that they must add words before using casual mode. But that's just a suggestion - go with whatever you had in mind!

i like this! i didnt really have anything in mind, EDIT: now its working again im confused

**Comment by DihyahAdib** [comment]
image
i dont understand why removing the strings made it work.

**Comment by nickmanning214** [comment]
Lol - Can't explain that. If you provide the fallback strings it should show if you pass undefined. And then if you don't then the card itself would say "undefined" on it. Either way it should not throw the error you were seeing in the console.

**Comment by DihyahAdib** [comment]
hm for some reason this just randomly breaks, its like it doesnt update the flash cards onload and displays undefined without any errors even with words in the wordbank
image

**Comment by DihyahAdib** [comment]
i console logged wordObj in the function and it does return the array of word, definition objects but it just isnt displaying like its supposed to 
image
image

**Comment by DihyahAdib** [comment]
just pushing the things we did on call

**Pull request merged**
